### PR TITLE
selected items will be stored in database

### PR DESCRIPTION
**Pull request by azimsodikov**

### CODE REVIEW

**Comment by jordandhaenens** [comment]
Hey Azim, 

When I ran grunt I get this error message: 
  Running "browserify:js" (browserify) task
  >> Error: Cannot find module 'firebase' from '/Users/j/workspace/group-projects/d19-group-
  theme-park-mustache/JS'

Any ideas where this module is?

**Comment by azimsodikov** [comment]
make sure your package json has firebase installed as dependancy
`npm install firebase --save`

**Comment by jordandhaenens** [comment]
That allowed grunt to run and create a new dist/app.js but the 'Selected Attractions' modal isn't populating now. The 'Add' button is still deleting attractions from the area modals.

**Comment by azimsodikov** [comment]
it should be populating but font color is white so the module, either should be changed!

**Comment by azimsodikov** [comment]
when add button is clicked it will add to the selected attractions module and delete it from attractions module, that should be right! unless we wanna still keep it when add pressed

**Comment by wpruitt** [comment]
I think we do want to make sure the modals always show all the possible attractions. Maybe we could indicate that the rides are saved somehow? Other than that 👍

**Pull request merged**
